name: Docker build and push

on:
  push:
    # tags:
    #  - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
    - uses: actions/checkout@v4

    - name: Set version
      run: |
        # Generate version using commit count and short SHA
        COMMIT_COUNT=$(git rev-list --count HEAD)
        SHORT_SHA=${GITHUB_SHA:0:7}
        VERSION="1.0.${COMMIT_COUNT}-${SHORT_SHA}"
        echo "RELEASE_VERSION=${VERSION}" >> $GITHUB_ENV

    - name: Test version
      run: |
        echo "Generated version: $RELEASE_VERSION"
        echo "Version from env: ${{ env.RELEASE_VERSION }}"

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      run: |
        docker build src -t ghcr.io/${{ github.repository_owner }}/carapi:${{ env.RELEASE_VERSION }} -t ghcr.io/${{ github.repository_owner }}/carapi:latest
        docker push ghcr.io/${{ github.repository_owner }}/carapi:${{ env.RELEASE_VERSION }}
        docker push ghcr.io/${{ github.repository_owner }}/carapi:latest